[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g pnpm",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "node apps/server/dist/index.js"
